name: Build and deploy a Spring app to App Service

on:
  push:
    branches:
      springdemo

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      
    # Check out repo to the VM
    - uses: actions/checkout@v1
    
    # Maven build
    - name: Build and test with Maven
      run: mvn clean package

    # Finally, deploy the container to App Service
    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'spring-one-demo'
        publish-profile: ${{ secrets.CREDENTIALS }}
        package: 'target/app.jar'

    - uses: azure/webapps-deploy@v1
      with:
        app-name: 'freebergwindowsjavase'
        publish-profile: ${{ secrets.PUB_PROFILE_FREEBERGWINDOWSJAVASE }}
        package: 'target/app.jar'